### ISSUE TITLE
Make processing work with rectangular arrays

### ISSUE THREAD

**Issue by pptman** [andreabassi78/napari-sim-processor#16]
Branch `rectangular` has been created for development of the sim processor class so that it can deal with rectangular arrays.  Testing of all methods used in the napari plug-in are successful so far, including GPU processing.  

Most changes are in the `baseSimProcessor.py` but some also in `_sim_widget.py` to cope with the fact that frequency plane images are now rectangular too and circular annotations need to be placed correctly and/or replaced with ellipses.

**Comment by pptman** [comment]
@andreabassi78 Check that this is working OK for you, please.

If we are happy with rectangular frequency plane images for `xcorr` and `spectrum` then I don't think we need to reshape these for display.

**Comment by andreabassi78** [comment]
Hi @pptman, I have tested the code and it works, the xcorr and spectrum are rectangular (with ellipses for the circles) and I also don't think this should be changed.
I also made some changes to this branch to fix the visualization issue that we had with python 3.10 (some of the changes are the same that you made in the fixesforpython3.10 branch).

We could promote this branch to the main one. What do you think?
I am not familiar with branch merging, and I'm not sure what are the correct steps (we now have at least 3 branches to merge: rectangular, fixesforpython3.10, ra_sim).

Can you let me know if everything works on your mac?
(I have changed some dependencies too, please let me know if this is causing problems)

**Comment by pptman** [comment]
@andreabassi78 I have done the merge.  Rectangular and fixesforpython3.1 were trivial as they are the same branch really.  ra_sim got a bit messy but with the right merge tool (I use pycharm's internal merge) it was easy to sort out.  It would on my mac with both my 3.9 and 3.10 versions, even after upgrading magicgui.  If you want to test the final merged version to make sure I haven't done anything wrong it is now on branch main again.  I'm not sure where you have changed dependencies (I can't see it in the git history) so am not really sure how to test this.

**Comment by pptman** [comment]
@andreabassi78 I notice the import changes that you have made but these don't work on my machine when running from pycharm (maybe I need to set something up?).  The error message is:
```
    from .baseSimProcessor import BaseSimProcessor
ImportError: attempted relative import with no known parent package
```
I also noticed the failed tox tests.  I noticed that one failure was to do with two environment variables on one line.  Meizhu found this too and we fixed it on the simulator but alas not here!

**Comment by pptman** [comment]
@andreabassi78 I took a look at the import error message I was getting and it seems that a better structure for us would be to move all the processing code into its own submodule, then the `from .baseSimProcessor import BaseSimProcessor` lines will work.  This works for me when running the code from within pycharm.  I have put the changes in a new branch `processors_submodule`.  I will test this from my jupyter notebook too.

Looking at the error messages from the tests it seems to be the line importing from module widget_settings that is not working.  I suspect this may be a related problem?

**Comment by pptman** [comment]
@andreabassi78 there is a solution that seems to work in branch `processors_submodule` but I suspect that this is not the real way to do it.

**Comment by pptman** [comment]
I pushed this branch as branch `npe2` in order to trigger the testing workflow and it passes.  I agree, this is probably not the correct way to do it, though you could argue that the `if__name__ == "__main__"` is just catching the case when you are trying to run the code directly during testing/development.  So maybe the code used by `else:` is the correct way to write things.

**Comment by andreabassi78** [comment]
@pptman Great to add the submodule processors, it makes the project clearer, even if it does not solve the dependencies project.
Adding the dots in e.g. "from .processors.hexSimProcessor import HexSimProcessor" is the right way to work with the module. 
I looked at a few other plugins and nobody runs the script directly. 

Therefore, [in another project](https://github.com/andreabassi78/napari-psf-simulator/tree/main/src), I decided to remove the `if __name__ == '__main__'` part from the `_widget.py` file and create a [separate py script](https://github.com/andreabassi78/napari-psf-simulator/blob/main/src/_widget_runner.py) to run the plugin.
It works, and it avoids the possible confusion of having if/else.

Please note that the `_widget_runner.py` file must be in the folder src. Having the `_widget_runner.py` in a separate file and folder might be uncomfortable but it makes the package clearer.
Some hints are [here](https://iq-inc.com/importerror-attempted-relative-import/#packages-explained).

I would use this same approach for the sim-processor plugin if you like it.

**Comment by pptman** [comment]
I agree, remove the __main__ stuff from the main code and create a short runner script in src.  In fact src is where I have to put my jupyter notebook to get that to run correctly too.

Mark

From: Andrea Bassi ***@***.***>
Date: Wednesday, 1 February 2023 at 07:36
To: andreabassi78/napari-sim-processor ***@***.***>
Cc: Neil, Mark A A ***@***.***>, Mention ***@***.***>
Subject: Re: [andreabassi78/napari-sim-processor] Make processing work with rectangular arrays (Issue #16)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



@pptman<https://github.com/pptman> Great to add the submodule processors, it makes the project clearer, even if it does not solve the dependencies project.
Adding the dots in e.g. "from .processors.hexSimProcessor import HexSimProcessor" is the right way to work with the module.
I looked at a few other plugins and nobody runs the script directly.

Therefore, in another project<https://github.com/andreabassi78/napari-psf-simulator/tree/main/src>, I decided to remove the if __name__ == '__main__' part from the _widget.py file and create a separate py script<https://github.com/andreabassi78/napari-psf-simulator/blob/main/src/_widget_runner.py> to run the plugin.
It works, and it avoids the possible confusion of having if/else.

Please note that the _widget_runner.py file must be in the folder src. Having the _widget_runner.py in a separate file and folder might be uncomfortable but it makes the package clearer.
Some hints are here<https://iq-inc.com/importerror-attempted-relative-import/#packages-explained>.

I would use this same approach for the sim-processor plugin if you like it.

**Comment by andreabassi78** [comment]
Done, the runner is now in the src folder. Processing of rectangular passed all the tests. 
The rectangular processing deserves a new version.
A new version v0.0.10, is now available on the Napari Hub.
